"""Build the Kodi repository for the Unknown add-ons.

Usage:  py tools/build_repo.py        -> build for GitHub Pages (default, no IP involved)
        py tools/build_repo.py --lan  -> bake this PC's auto-detected LAN IP into the repo add-on
        set UNKNOWN_REPO_URL=...       -> override the base URL entirely
      (or double-click publish-update.bat for the Pages build + live push)

Writes repo/:
    addons.xml, addons.xml.md5          what Kodi reads to find new versions
    <addon id>/<addon id>-<version>.zip one zip per add-on, plus its icon/fanart
    repository.unknown-<version>.zip    copy at the top level, for installing the repository the first time

Default builds land on GitHub Pages at PAGES_URL, so a rebuild + push is live for every user
immediately. tools/repo_server.py can serve repo/ locally instead when publishing with --lan.
Raise an add-on's version in its addon.xml before building, or Kodi won't treat it as an update.
"""
import argparse
import hashlib
import os
import re
import shutil
import xml.etree.ElementTree as ET

from build_zips import ADDONS, ROOT, build

# Where the repository lives. Baked into the repository add-on, so it must be reachable from
# any Kodi device that wants updates. GitHub Pages always is; a LAN address only ever is
# reachable from the same house (and only while the serving PC is on).
PAGES_URL = "https://xxscrimxx.github.io/Kodi-Netflix/"

REPOSITORY_ID = "repository.unknown"
REPOSITORY_VERSION = "1.0.0"
REPO_DIR = ROOT / "repo"

REPO_URL = PAGES_URL


def lan_url():
    """This PC's LAN address as a repo URL, or "" if it cannot be determined.

    Uses a UDP probe that never actually sends a packet, so no traffic leaves the machine.
    """
    import socket
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            probe.connect(("8.8.8.8", 80))
            return "http://{}:8000/".format(probe.getsockname()[0])
        finally:
            probe.close()
    except OSError:
        return ""


def resolve_repo_url(lan):
    if os.environ.get("UNKNOWN_REPO_URL"):
        return os.environ["UNKNOWN_REPO_URL"]
    if lan:
        found = lan_url()
        if found:
            print("Repository URL: {} (auto-detected)".format(found))
            return found
        print("Could not detect a LAN address; falling back to " + PAGES_URL)
    return PAGES_URL


REPOSITORY_ADDON_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/build_repo.py; edit REPO_URL / REPOSITORY_VERSION there instead. -->
<addon id="{id}" name="Unknown Repository" version="{version}" provider-name="unknown">
	<extension point="xbmc.addon.repository" name="Unknown Repository">
		<dir>
			<info compressed="false">{url}addons.xml</info>
			<checksum>{url}addons.xml.md5</checksum>
			<datadir zip="true">{url}</datadir>
		</dir>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en_GB">Updates for the Unknown skin and add-ons.</summary>
		<description lang="en_GB">Automatic updates delivered through GitHub Pages - nothing to configure, no home network required.</description>
	</extension>
</addon>
"""


def write_repository_addon():
    addon_dir = ROOT / REPOSITORY_ID
    addon_dir.mkdir(exist_ok=True)
    (addon_dir / "addon.xml").write_text(
        REPOSITORY_ADDON_XML.format(id=REPOSITORY_ID, version=REPOSITORY_VERSION, url=REPO_URL), encoding="utf-8")


def manifest_entry(addon_id):
    """The add-on's addon.xml without its XML declaration, for embedding in addons.xml."""
    text = (ROOT / addon_id / "addon.xml").read_text(encoding="utf-8")
    return re.sub(r"^\s*<\?xml[^>]*\?>\s*", "", text).strip()


def copy_assets(addon_id, target_dir):
    """Kodi shows an add-on's icon and fanart in the repository browser by fetching them next to the zip."""
    for assets in ET.parse(ROOT / addon_id / "addon.xml").getroot().iter("assets"):
        for asset in assets:
            relative = (asset.text or "").strip()
            source = ROOT / addon_id / relative
            if relative and source.is_file():
                destination = target_dir / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)


def main():
    parser = argparse.ArgumentParser(description="Build the Unknown Kodi repository.")
    parser.add_argument("--lan", action="store_true",
                        help="bake this PC's auto-detected LAN address into the repository add-on")
    args = parser.parse_args()
    global REPO_URL
    REPO_URL = resolve_repo_url(args.lan)

    write_repository_addon()
    REPO_DIR.mkdir(exist_ok=True)

    entries = []
    for addon_id in (REPOSITORY_ID,) + ADDONS:
        target_dir = REPO_DIR / addon_id
        # Only the current version is published; older zips are removed.
        if target_dir.exists():
            shutil.rmtree(target_dir)
        target_dir.mkdir(parents=True)
        build(addon_id, target_dir)
        copy_assets(addon_id, target_dir)
        entries.append(manifest_entry(addon_id))

    addons_xml = ('<?xml version="1.0" encoding="UTF-8"?>\n<addons>\n' + "\n".join(entries) + "\n</addons>\n").encode("utf-8")
    (REPO_DIR / "addons.xml").write_bytes(addons_xml)
    (REPO_DIR / "addons.xml.md5").write_text(hashlib.md5(addons_xml).hexdigest(), encoding="ascii")

    repository_zip = "{}-{}.zip".format(REPOSITORY_ID, REPOSITORY_VERSION)
    for old in REPO_DIR.glob(REPOSITORY_ID + "-*.zip"):
        old.unlink()
    shutil.copy2(REPO_DIR / REPOSITORY_ID / repository_zip, REPO_DIR / repository_zip)

    print("\nPublished {} add-ons to {}".format(len(entries), REPO_URL))


if __name__ == "__main__":
    main()
